"""Descripción de los cambios

Revision ID: 1948319243ef
Revises: 
Create Date: 2024-06-23 09:45:13.267449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1948319243ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_proveedor', schema=None) as batch_op:
        batch_op.drop_column('lote_optimo')

    with op.batch_alter_table('estado_orden_compra', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('penditente', 'en_curso', 'finalizada', name='nombreestadocompra'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_orden_compra', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.Enum('penditente', 'en_curso', 'finalizada', name='nombreestadocompra'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('detalle_proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lote_optimo', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
