"""errorDemandaPredecida2

Revision ID: 3d21c1a3b231
Revises: 0138fe2d5c67
Create Date: 2024-06-28 09:49:10.549776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d21c1a3b231'
down_revision = '0138fe2d5c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_demanda_predecida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('articulo_ID', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'articulo', ['articulo_ID'], ['id'])
        batch_op.drop_column('articulo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_demanda_predecida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('articulo_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'articulo', ['articulo_id'], ['id'])
        batch_op.drop_column('articulo_ID')

    # ### end Alembic commands ###
