"""Descripción de los cambios

Revision ID: 647f6368fcda
Revises: 1948319243ef
Create Date: 2024-06-23 16:48:11.750674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647f6368fcda'
down_revision = '1948319243ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_orden_compra', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_orden_compra', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
