"""crear tablas

Revision ID: d42e0f2e0940
Revises: 
Create Date: 2024-06-17 02:06:44.884240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42e0f2e0940'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('columna_temporal', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.drop_column('columna_temporal')

    # ### end Alembic commands ###
