"""cambios

Revision ID: f9402ff1fb10
Revises: d42e0f2e0940
Create Date: 2024-06-17 02:08:36.971094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9402ff1fb10'
down_revision = 'd42e0f2e0940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.drop_column('columna_temporal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('columna_temporal', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
